// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ciphertexts.proto

#include "ciphertexts.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace HomPSI {
constexpr Ciphertexts::Ciphertexts(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : ciphertexts_(){}
struct CiphertextsDefaultTypeInternal {
  constexpr CiphertextsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~CiphertextsDefaultTypeInternal() {}
  union {
    Ciphertexts _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT CiphertextsDefaultTypeInternal _Ciphertexts_default_instance_;
}  // namespace HomPSI
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ciphertexts_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ciphertexts_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ciphertexts_2eproto = nullptr;

const uint32_t TableStruct_ciphertexts_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HomPSI::Ciphertexts, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HomPSI::Ciphertexts, ciphertexts_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::HomPSI::Ciphertexts)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::HomPSI::_Ciphertexts_default_instance_),
};

const char descriptor_table_protodef_ciphertexts_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021ciphertexts.proto\022\006HomPSI\"\"\n\013Ciphertex"
  "ts\022\023\n\013cipherTexts\030\001 \003(\014"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ciphertexts_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ciphertexts_2eproto = {
  false, false, 63, descriptor_table_protodef_ciphertexts_2eproto, "ciphertexts.proto", 
  &descriptor_table_ciphertexts_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_ciphertexts_2eproto::offsets,
  file_level_metadata_ciphertexts_2eproto, file_level_enum_descriptors_ciphertexts_2eproto, file_level_service_descriptors_ciphertexts_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_ciphertexts_2eproto_getter() {
  return &descriptor_table_ciphertexts_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_ciphertexts_2eproto(&descriptor_table_ciphertexts_2eproto);
namespace HomPSI {

// ===================================================================

class Ciphertexts::_Internal {
 public:
};

Ciphertexts::Ciphertexts(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  ciphertexts_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:HomPSI.Ciphertexts)
}
Ciphertexts::Ciphertexts(const Ciphertexts& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      ciphertexts_(from.ciphertexts_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:HomPSI.Ciphertexts)
}

inline void Ciphertexts::SharedCtor() {
}

Ciphertexts::~Ciphertexts() {
  // @@protoc_insertion_point(destructor:HomPSI.Ciphertexts)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Ciphertexts::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Ciphertexts::ArenaDtor(void* object) {
  Ciphertexts* _this = reinterpret_cast< Ciphertexts* >(object);
  (void)_this;
}
void Ciphertexts::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Ciphertexts::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Ciphertexts::Clear() {
// @@protoc_insertion_point(message_clear_start:HomPSI.Ciphertexts)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ciphertexts_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Ciphertexts::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated bytes cipherTexts = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_ciphertexts();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Ciphertexts::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HomPSI.Ciphertexts)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated bytes cipherTexts = 1;
  for (int i = 0, n = this->_internal_ciphertexts_size(); i < n; i++) {
    const auto& s = this->_internal_ciphertexts(i);
    target = stream->WriteBytes(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HomPSI.Ciphertexts)
  return target;
}

size_t Ciphertexts::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HomPSI.Ciphertexts)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated bytes cipherTexts = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(ciphertexts_.size());
  for (int i = 0, n = ciphertexts_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      ciphertexts_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Ciphertexts::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Ciphertexts::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Ciphertexts::GetClassData() const { return &_class_data_; }

void Ciphertexts::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Ciphertexts *>(to)->MergeFrom(
      static_cast<const Ciphertexts &>(from));
}


void Ciphertexts::MergeFrom(const Ciphertexts& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HomPSI.Ciphertexts)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  ciphertexts_.MergeFrom(from.ciphertexts_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Ciphertexts::CopyFrom(const Ciphertexts& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HomPSI.Ciphertexts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ciphertexts::IsInitialized() const {
  return true;
}

void Ciphertexts::InternalSwap(Ciphertexts* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ciphertexts_.InternalSwap(&other->ciphertexts_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Ciphertexts::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_ciphertexts_2eproto_getter, &descriptor_table_ciphertexts_2eproto_once,
      file_level_metadata_ciphertexts_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace HomPSI
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::HomPSI::Ciphertexts* Arena::CreateMaybeMessage< ::HomPSI::Ciphertexts >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HomPSI::Ciphertexts >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
