// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ciphertexts.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ciphertexts_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ciphertexts_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ciphertexts_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ciphertexts_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ciphertexts_2eproto;
namespace HomPSI {
class Ciphertexts;
struct CiphertextsDefaultTypeInternal;
extern CiphertextsDefaultTypeInternal _Ciphertexts_default_instance_;
}  // namespace HomPSI
PROTOBUF_NAMESPACE_OPEN
template<> ::HomPSI::Ciphertexts* Arena::CreateMaybeMessage<::HomPSI::Ciphertexts>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace HomPSI {

// ===================================================================

class Ciphertexts final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HomPSI.Ciphertexts) */ {
 public:
  inline Ciphertexts() : Ciphertexts(nullptr) {}
  ~Ciphertexts() override;
  explicit constexpr Ciphertexts(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Ciphertexts(const Ciphertexts& from);
  Ciphertexts(Ciphertexts&& from) noexcept
    : Ciphertexts() {
    *this = ::std::move(from);
  }

  inline Ciphertexts& operator=(const Ciphertexts& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ciphertexts& operator=(Ciphertexts&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Ciphertexts& default_instance() {
    return *internal_default_instance();
  }
  static inline const Ciphertexts* internal_default_instance() {
    return reinterpret_cast<const Ciphertexts*>(
               &_Ciphertexts_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Ciphertexts& a, Ciphertexts& b) {
    a.Swap(&b);
  }
  inline void Swap(Ciphertexts* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Ciphertexts* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Ciphertexts* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Ciphertexts>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Ciphertexts& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Ciphertexts& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ciphertexts* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HomPSI.Ciphertexts";
  }
  protected:
  explicit Ciphertexts(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCipherTextsFieldNumber = 1,
  };
  // repeated bytes cipherTexts = 1;
  int ciphertexts_size() const;
  private:
  int _internal_ciphertexts_size() const;
  public:
  void clear_ciphertexts();
  const std::string& ciphertexts(int index) const;
  std::string* mutable_ciphertexts(int index);
  void set_ciphertexts(int index, const std::string& value);
  void set_ciphertexts(int index, std::string&& value);
  void set_ciphertexts(int index, const char* value);
  void set_ciphertexts(int index, const void* value, size_t size);
  std::string* add_ciphertexts();
  void add_ciphertexts(const std::string& value);
  void add_ciphertexts(std::string&& value);
  void add_ciphertexts(const char* value);
  void add_ciphertexts(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& ciphertexts() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_ciphertexts();
  private:
  const std::string& _internal_ciphertexts(int index) const;
  std::string* _internal_add_ciphertexts();
  public:

  // @@protoc_insertion_point(class_scope:HomPSI.Ciphertexts)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> ciphertexts_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ciphertexts_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Ciphertexts

// repeated bytes cipherTexts = 1;
inline int Ciphertexts::_internal_ciphertexts_size() const {
  return ciphertexts_.size();
}
inline int Ciphertexts::ciphertexts_size() const {
  return _internal_ciphertexts_size();
}
inline void Ciphertexts::clear_ciphertexts() {
  ciphertexts_.Clear();
}
inline std::string* Ciphertexts::add_ciphertexts() {
  std::string* _s = _internal_add_ciphertexts();
  // @@protoc_insertion_point(field_add_mutable:HomPSI.Ciphertexts.cipherTexts)
  return _s;
}
inline const std::string& Ciphertexts::_internal_ciphertexts(int index) const {
  return ciphertexts_.Get(index);
}
inline const std::string& Ciphertexts::ciphertexts(int index) const {
  // @@protoc_insertion_point(field_get:HomPSI.Ciphertexts.cipherTexts)
  return _internal_ciphertexts(index);
}
inline std::string* Ciphertexts::mutable_ciphertexts(int index) {
  // @@protoc_insertion_point(field_mutable:HomPSI.Ciphertexts.cipherTexts)
  return ciphertexts_.Mutable(index);
}
inline void Ciphertexts::set_ciphertexts(int index, const std::string& value) {
  ciphertexts_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:HomPSI.Ciphertexts.cipherTexts)
}
inline void Ciphertexts::set_ciphertexts(int index, std::string&& value) {
  ciphertexts_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:HomPSI.Ciphertexts.cipherTexts)
}
inline void Ciphertexts::set_ciphertexts(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  ciphertexts_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:HomPSI.Ciphertexts.cipherTexts)
}
inline void Ciphertexts::set_ciphertexts(int index, const void* value, size_t size) {
  ciphertexts_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:HomPSI.Ciphertexts.cipherTexts)
}
inline std::string* Ciphertexts::_internal_add_ciphertexts() {
  return ciphertexts_.Add();
}
inline void Ciphertexts::add_ciphertexts(const std::string& value) {
  ciphertexts_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:HomPSI.Ciphertexts.cipherTexts)
}
inline void Ciphertexts::add_ciphertexts(std::string&& value) {
  ciphertexts_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:HomPSI.Ciphertexts.cipherTexts)
}
inline void Ciphertexts::add_ciphertexts(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  ciphertexts_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:HomPSI.Ciphertexts.cipherTexts)
}
inline void Ciphertexts::add_ciphertexts(const void* value, size_t size) {
  ciphertexts_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:HomPSI.Ciphertexts.cipherTexts)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Ciphertexts::ciphertexts() const {
  // @@protoc_insertion_point(field_list:HomPSI.Ciphertexts.cipherTexts)
  return ciphertexts_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Ciphertexts::mutable_ciphertexts() {
  // @@protoc_insertion_point(field_mutable_list:HomPSI.Ciphertexts.cipherTexts)
  return &ciphertexts_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace HomPSI

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ciphertexts_2eproto
